spring.application.name=alumnos

spring.datasource.url=jdbc:mysql://alumnosdb.clwm2igoc5xi.us-east-2.rds.amazonaws.com:3306/alumnosdb
spring.datasource.username=admin
spring.datasource.password=SAYUMI14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 🔥 IMPORTANTE para Railway
server.port=${PORT:8080}
server.address=0.0.0.0