spring.application.name=alumnos

spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:16491/railway
spring.datasource.username=root
spring.datasource.password=UaFkWctkxboyUSEChHNuIxvdyHjniRdI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}